const ADMIN='jailtonsilas48@gmail.com';
const app=document.querySelector('#app'); const $=s=>document.querySelector(s);

// LinkFinity v16.1 CLEAN
// Sem streamers mockados, sem presentes/efeitos mockados e sem localStorage.
// ATENÇÃO: esta versão mantém dados só em memória para não salvar nada localmente.
// Para ficar 100% real, conectar estas funções a Supabase/Neon/Firebase + backend Pix/TikTok.
const state={
  user:null,
  coins:0,
  withdrawBalance:0,
  gifts:[],
  streamers:[],
  events:[],
  purchases:[],
  inventory:[]
};

const imgDefault='data:image/svg+xml;utf8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#367cff"/><stop offset="1" stop-color="#7c3aed"/></linearGradient></defs><rect width="200" height="200" rx="46" fill="#111827"/><path d="M100 35l17 39 42 4-32 28 10 42-37-22-37 22 10-42-32-28 42-4z" fill="url(#g)"/><text x="100" y="174" text-anchor="middle" fill="#fff" font-family="Arial" font-weight="900" font-size="24">LF</text></svg>');
function ico(n){const p={home:'M3 11l9-8 9 8v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1v-9z',gift:'M20 12v9H4v-9M12 7v14M4 7h16v5H4zM12 7H8.5a2.5 2.5 0 1 1 2.5-2.5V7zm0 0h3.5A2.5 2.5 0 1 0 13 4.5V7z',wallet:'M20 7H5a2 2 0 0 1 0-4h13v4M3 7v12a2 2 0 0 0 2 2h15V7H3zm13 7h2',chart:'M4 19V5M8 17v-6M13 17V7M18 17v-9M3 19h18',user:'M20 21a8 8 0 0 0-16 0M12 13a5 5 0 1 0 0-10 5 5 0 0 0 0 10z',settings:'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zM19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21a2 2 0 1 1-4 0v-.09A1.7 1.7 0 0 0 8.6 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3a2 2 0 1 1 0-4h.09A1.7 1.7 0 0 0 4.6 8.6a1.7 1.7 0 0 0-.34-1.88l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.7 1.7 0 0 0 9 4.6c.38 0 .74-.13 1-.36.37-.28.6-.7.6-1.17V3a2 2 0 1 1 4 0v.09c0 .47.23.89.6 1.17.26.23.62.36 1 .36.7 0 1.35-.27 1.88-.74l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.7 1.7 0 0 0 19.4 9c0 .38.13.74.36 1 .28.37.7.6 1.17.6H21a2 2 0 1 1 0 4h-.09c-.47 0-.89.23-1.17.6-.23.26-.36.62-.36 1z',search:'M21 21l-4.3-4.3M10.5 18a7.5 7.5 0 1 1 0-15 7.5 7.5 0 0 1 0 15z',spark:'M12 2l2.4 6.6L21 11l-6.6 2.4L12 20l-2.4-6.6L3 11l6.6-2.4z',shield:'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z',copy:'M8 8h12v12H8zM4 16V4h12'};return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="${p[n]||p.spark}"/></svg>`}
function logo(){return `<div class="logo-mark"><svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.5"><path d="M12 3l7 18-7-4-7 4 7-18z"/><path d="M9 14h6"/></svg></div>`}
function user(){return state.user} function coins(){return state.coins} function gifts(){return state.gifts} function events(){return state.events} function streamers(){return state.streamers}

function landing(){app.innerHTML=`<header class="topbar"><div class="brand">${logo()}<div class="brand-title"><span>Link</span><b>Finity</b></div></div><nav class="nav"><button class="active">Início</button><button>Ranking</button><button>Premium</button><button>Comunidade</button></nav><button class="btn" onclick="login()">${ico('home')} Dashboard</button></header><main class="landing"><span class="chip">${ico('spark')} Seja membro agora da LinkFinity</span><h1 class="hero"><span>Toda a sua personalidade</span><br/>em um só lugar</h1><p class="sub">Plataforma visual para streamers criarem presentes, receberem LinkCoins e usarem um overlay transparente profissional no TikTok Live Studio.</p><div class="actions"><button class="btn" onclick="login()">Dashboard →</button><button class="btn dark" onclick="login()">${ico('spark')} Conhecer o premium</button></div><div class="stats"><div class="stat"><small>${ico('user')} Usuários</small><h2>14.84k</h2></div><div class="stat"><small>${ico('copy')} Overlays</small><h2>7.66k</h2></div><div class="stat"><small>${ico('gift')} Gifts</small><h2>48.77k</h2></div></div><div class="feature-grid"><div class="card shine"><h3>${ico('gift')} Presentes próprios</h3><p>Cards modernos com imagem, preço, categoria e raridade.</p></div><div class="card shine"><h3>${ico('copy')} Overlay único</h3><p>Um único link /overlay recebe todos os presentes enviados.</p></div><div class="card shine"><h3>${ico('chart')} Ranking</h3><p>Top apoiadores, últimos envios e ganhos em cards.</p></div></div></main>`}
function login(){app.innerHTML=`<main class="login-page"><section class="login-art"><div class="brand">${logo()}<div class="brand-title"><span>Link</span><b>Finity</b></div></div><div><span class="chip">${ico('spark')} Visual premium</span><h1>Entre no seu painel de streamer.</h1><p class="sub" style="margin:0;text-align:left">Login pronto visualmente. Para TikTok real, conecte OAuth pelo backend conforme passo a passo.</p></div><div class="feature-grid" style="grid-template-columns:1fr 1fr;margin:0"><div class="card"><b>Overlay transparente</b><p>Sem texto, sem fundo, só a animação.</p></div><div class="card"><b>LinkCoins</b><p>Carteira e presentes no mesmo painel.</p></div></div></section><section class="login-card"><h2>Entrar na LinkFinity</h2><p class="muted">Versão limpa sem localStorage. O login abaixo é apenas visual até conectar OAuth/DB.</p><button class="btn tiktok" onclick="tiktokRealInfo()">Entrar com TikTok</button><div class="divider">ou continue em modo teste sem salvar local</div><input id="email" class="input" value="jailtonsilas48@gmail.com" placeholder="Email"><br><br><input id="name" class="input" value="Jailton Silas" placeholder="Nome público"><br><br><button class="btn" style="width:100%" onclick="doLogin()">Acessar dashboard</button><br><br><button class="btn ghost" style="width:100%" onclick="landing()">Voltar</button></section></main>`}
function doLogin(){const email=$('#email').value.trim(),name=$('#name').value.trim()||email.split('@')[0];if(!email)return toast('Digite o email');state.user={email,name,username:name.toLowerCase().replace(/\s+/g,''),photo:imgDefault};dash('home')}
function tiktokRealInfo(){toast('Conecte OAuth real no backend. Passo a passo enviado no chat.')}
function logout(){state.user=null;landing()}
function shell(page,title,body){const u=user();app.innerHTML=`<div class="layout"><aside class="side"><div class="brand">${logo()}<div class="brand-title"><span>Link</span><b>Finity</b></div></div><div class="section-label">Painel</div>${nav('home','Dashboard',page,'home')}${nav('explore','Explorar Streamers',page,'search')}${nav('wallet','Carteira',page,'wallet')}${nav('gifts','Presentes',page,'gift')}${nav('widgets','Widgets / Overlay',page,'copy')}${nav('earnings','Ganhos',page,'chart')}${u.email===ADMIN?nav('admin','Admin',page,'shield'):''}<div class="section-label">Conta</div>${nav('settings','Configurações',page,'settings')}<div class="profile-mini"><div class="avatar"><img src="${u.photo||imgDefault}"></div><div style="min-width:0"><b>${u.name}</b><div class="muted" style="font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">@${u.username}</div></div><button class="btn small dark" onclick="logout()">Sair</button></div></aside><main class="main"><header class="head"><div><div class="muted" style="font-weight:850">LinkFinity / ${title}</div><h1>${title}</h1></div><button class="btn" onclick="dash('wallet')">${ico('wallet')} ${coins()} coins</button></header><section class="content">${body}</section></main></div>`}
function nav(p,label,cur,icon){return `<button class="link ${cur===p?'active':''}" onclick="dash('${p}')">${ico(icon)} ${label}</button>`}
function dash(p='home'){if(!user())return login();if(p==='wallet')return wallet('recarga');if(p==='gifts')return giftShop('Todos');if(p==='explore')return explore();if(p==='widgets')return widgets();if(p==='earnings')return earnings();if(p==='admin')return admin();if(p==='settings')return settings();const ev=events();shell('home','Dashboard',`<div class="dashboard-grid"><div class="metric"><div class="topline">Saldo ${ico('wallet')}</div><h2>${coins()}</h2><span class="muted">LinkCoins disponíveis</span></div><div class="metric"><div class="topline">Presentes ${ico('gift')}</div><h2>${gifts().length}</h2><span class="muted">gifts cadastrados</span></div><div class="metric"><div class="topline">Ganhos ${ico('chart')}</div><h2>R$ ${state.withdrawBalance.toFixed(2).replace('.',',')}</h2><span class="muted">saldo disponível para saque</span></div><div class="metric"><div class="topline">Streamers ${ico('user')}</div><h2>${streamers().length}</h2><span class="muted">perfis reais conectados</span></div></div><div class="two-col"><div class="card"><h2>Atividade recente</h2>${activityList()}</div><div class="card"><h2>Atalho rápido</h2><p>Copie seu overlay e adicione como origem web no TikTok Live Studio.</p><button class="btn" onclick="dash('widgets')">Abrir overlay</button></div></div>`) }
function activityList(){const ev=events().slice(-5).reverse();return ev.length?ev.map(e=>`<div class="activity"><img src="${e.gift.img}"><div><b>${e.from}</b><p>enviou ${e.gift.name} • <span class="price">${e.coins} coins</span></p></div></div>`).join(''):'<div class="empty">Nenhum presente enviado ainda.</div>'}
function wallet(tab='recarga'){const tabs=`<div class="tabs"><button class="${tab==='recarga'?'active':''}" onclick="wallet('recarga')">${ico('wallet')} Recarga</button><button class="${tab==='inventario'?'active':''}" onclick="wallet('inventario')">${ico('gift')} Inventário</button><button class="${tab==='historico'?'active':''}" onclick="wallet('historico')">${ico('chart')} Histórico</button></div>`;let body='';if(tab==='recarga'){body=`<div class="wallet-grid">${[[100,5,'Starter'],[500,20,'Popular'],[1000,35,'Melhor valor'],[2500,80,'Pro'],[5000,150,'Premium']].map(x=>`<div class="coin shine"><span class="badge">${x[2]}</span><h2>${x[0]} LinkCoins</h2><p>Pix real entra no próximo passo. Pacote: R$ ${x[1]},00</p><button class="btn" onclick="startPix(${x[0]},${x[1]})">Recarregar</button></div>`).join('')}</div>`}if(tab==='inventario'){body=`<div class="card"><h2>Inventário</h2>${state.inventory.length?state.inventory.map(i=>`<div class="activity"><img src="${i.img}"><div><b>${i.name}</b><p>${i.type||'Item'}</p></div></div>`).join(''):'<div class="empty">Nenhum item no inventário ainda.</div>'}</div>`}if(tab==='historico'){body=`<div class="card"><h2>Histórico</h2>${state.purchases.length?state.purchases.map(p=>`<div class="activity"><div><b>${p.title}</b><p>${p.desc}</p></div></div>`).join(''):'<div class="empty">Nenhuma movimentação ainda.</div>'}</div>`}shell('wallet','Carteira',tabs+body)}
function startPix(coinsAmount,brl){state.purchases.unshift({title:`Pix pendente: ${coinsAmount} LinkCoins`,desc:`R$ ${brl},00 — conecte Mercado Pago/Gerencianet no backend para gerar QR Code real.`});toast('Pix real será conectado no backend. Histórico atualizado.');wallet('historico')}
function giftCard(g){return `<div class="gift shine"><div class="gift-img"><img src="${g.img}" onerror="this.src='${imgDefault}'"></div><span class="badge">${g.rarity}</span><h3>${g.name}</h3><p class="muted">${g.desc||g.cat}</p><p>Preço: <span class="price">${g.price} LinkCoins</span></p><div style="display:flex;gap:8px"><button class="btn small" onclick="sendGift(${g.id})">${ico('gift')} Enviar</button><button class="btn small dark" onclick="previewGift(${g.id})">Visualizar</button></div></div>`}
function giftShop(cat){const all=gifts();const list=cat==='Todos'?all:all.filter(g=>g.cat===cat);shell('gifts','Presentes',`<div class="tabs">${['Todos','Presentes','Interativo','Exclusivo'].map(t=>`<button class="${cat===t?'active':''}" onclick="giftShop('${t}')">${ico(t==='Todos'?'gift':'spark')} ${t}</button>`).join('')}</div><div class="gift-grid">${list.map(giftCard).join('')||'<div class="empty">Nenhum presente cadastrado ainda. Crie pelo Admin.</div>'}</div>`)}
function admin(){if(user().email!==ADMIN)return dash('home');shell('admin','Admin',`<div class="card" style="margin-bottom:18px"><h2>Criar presente</h2><p>Cadastre imagem/GIF por URL. Ela aparece no card e no overlay transparente.</p><div class="form-grid"><input id="gname" class="input" placeholder="Nome"><input id="gprice" class="input" type="number" placeholder="Preço em coins"><select id="gcat" class="input"><option>Presentes</option><option>Interativo</option><option>Exclusivo</option></select><input id="grarity" class="input" placeholder="Raridade"><input id="gimg" class="input" style="grid-column:1/-1" placeholder="URL da imagem/GIF"></div><br><button class="btn" onclick="saveGift()">Criar presente</button></div><div class="gift-grid">${gifts().map(giftCard).join('')||'<div class="empty">Nenhum presente/efeito mockado. Cadastre seus próprios itens aqui.</div>'}</div>`)}
function saveGift(){let g={id:Date.now(),name:$('#gname').value||'Presente',price:+$('#gprice').value||0,cat:$('#gcat').value,rarity:$('#grarity').value||'Comum',img:$('#gimg').value||imgDefault,desc:'Presente criado pelo admin'};state.gifts=[...gifts(),g];state.purchases.unshift({title:'Presente criado',desc:g.name});toast('Presente criado');admin()}
function explore(){shell('explore','Explorar Streamers',`<div class="card"><input class="input" id="q" placeholder="Pesquisar streamer real por @username" oninput="exploreFilter()"><p class="muted">Nenhum streamer mockado. Quando conectar TikTok/Supabase, usuários reais aparecem aqui.</p></div><br><div id="streamers">${streamers().map(streamerCard).join('')||'<div class="empty">Nenhum streamer real conectado ainda.</div>'}</div>`)}
function streamerCard(s){return `<div class="streamer-card"><img src="${s.photo}"><div style="flex:1"><h2 style="margin:0">${s.name}</h2><p class="muted">@${s.username} • ${s.followers||0} seguidores</p></div><button class="btn" onclick="dash('gifts')">Enviar presente</button></div>`}
function exploreFilter(){const q=$('#q').value.toLowerCase();$('#streamers').innerHTML=streamers().filter(s=>s.username.includes(q)||s.name.toLowerCase().includes(q)).map(streamerCard).join('')||'<div class="empty">Nenhum streamer encontrado.</div>'}
function widgets(){const url=location.origin+location.pathname.replace('index.html','')+'overlay.html?streamer='+user().username;const preview=gifts()[0]?.img||imgDefault;shell('widgets','Widgets / Overlay',`<div class="two-col"><div class="card"><div class="widget-preview"><img src="${preview}"></div><h2>Gift overlay</h2><p>Overlay único e transparente. Todos os presentes enviados aparecem aqui.</p><button class="btn" onclick="testOverlay()">Testar alerta</button></div><div class="card"><h2>URL do widget</h2><p>Adicione como origem web no TikTok Live Studio.</p><div class="copybox"><input class="input" id="ovurl" value="${url}" readonly><button class="btn" onclick="copyUrl()">${ico('copy')} Copiar</button></div><hr style="border:0;border-top:1px solid #303a4e;margin:20px 0"><h3>Recomendado</h3><p>Largura 800px<br>Altura 450px<br>Fundo transparente</p></div></div>`)}
function copyUrl(){navigator.clipboard?.writeText($('#ovurl').value);toast('URL copiada')}
function sendGift(id){const g=gifts().find(x=>x.id===id);if(!g)return;const c=coins();if(c<g.price)return toast('Saldo insuficiente');state.coins=c-g.price;fire(g);toast('Presente enviado para o overlay')}
function previewGift(id){const g=gifts().find(x=>x.id===id);fire(g);toast('Prévia enviada')}
function testOverlay(){fire(gifts()[0]||{name:'Teste',price:0,img:imgDefault});toast('Teste enviado')}
function fire(g){const ev={id:Date.now(),gift:g,from:user()?.name||'Viewer',coins:g.price,streamer:user()?.username||'linkfinity'};state.events=[...events(),ev];state.withdrawBalance += Number(((g.price||0)*0.01).toFixed(2));if(window.BroadcastChannel){const bc=new BroadcastChannel('linkfinity_overlay');bc.postMessage(ev);bc.close()}}
function earnings(){const ev=events();shell('earnings','Ganhos',`<div class="dashboard-grid"><div class="metric"><div class="topline">Saldo para saque</div><h2>R$ ${state.withdrawBalance.toFixed(2).replace('.',',')}</h2><span class="muted">dinheiro real do streamer</span></div><div class="metric"><div class="topline">Presentes</div><h2>${ev.length}</h2><span class="muted">envios recebidos</span></div><div class="metric"><div class="topline">Coins recebidos</div><h2>${ev.reduce((a,e)=>a+(e.coins||0),0)}</h2><span class="muted">convertidos em saldo</span></div></div><br><div class="card"><h2>Últimos presentes</h2>${activityList()}</div>`)}
function settings(){shell('settings','Configurações',`<div class="card"><h2>Perfil</h2><p>Configuração visual em memória. Para salvar real, conecte banco de dados.</p><input id="setname" class="input" value="${user().name}"><br><br><button class="btn" onclick="state.user.name=$('#setname').value;toast('Perfil salvo na sessão');dash('settings')">Salvar</button></div>`)}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2400)}
window.addEventListener('load',landing);
